spring.cloud.stream:
  function:
    definition: userService
  bindings:
    userService-in-0:
      destination: equal.github-user
  kafka:
    bindings:
      userService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092
